CREATE TABLE BK444 (
    S# VARCHAR(8),
    C# VARCHAR(5),
    GRADE FLOAT4,
    DDATE DATE
);

CREATE OR REPLACE FUNCTION TRI_DELETE_FUNC() RETURNS TRIGGER AS
$$
DECLARE
BEGIN
    INSERT INTO BK444 
    (S#, C#, GRADE, DDATE)
    VALUES (
        OLD.S#,
        OLD.C#, 
        OLD.GRADE,
        NOW()
    );
    RETURN OLD;
END
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER delete_trigger
BEFORE DELETE ON SC444
FOR EACH ROW
EXECUTE PROCEDURE tri_delete_func();